[project]
name = 'drip-protocol'
description = 'DRIP - sBTC Streaming Payments. Bitcoin that flows.'
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.sbtc-token'
[contracts.drip-core]
path = 'contracts/drip-core-testnet.clar'
clarity_version = 4
epoch = 'latest'

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
